### ISSUE TITLE
Install module error

### ISSUE THREAD

**Issue by Smartbotz** [ERLANRAHMAT/BETABOTZ-MD2#23]
Bang kok pas install module pakai npm i itu malah error ada 4 type error ya kayak ada package yang error,ku coba lagi pake yarn install tetap masi error baileys nya .bin ngak bisa akses terus ku coba npm start erorr,intinya ada masalah ketika install module

**Comment by ERLANRAHMAT** [comment]
ss eror?detail eror?kirim erornya biar gw tau...

**Comment by RokhisAhmad** [comment]
![Screenshot_20231106-163032](https://github.com/ERLANRAHMAT/BETABOTZ-MD2/assets/92363825/f9102aa5-aff2-4f6d-beb7-f90ed6f77b55)
![Screenshot_20231106-163027](https://github.com/ERLANRAHMAT/BETABOTZ-MD2/assets/92363825/149323a4-9ded-4011-9333-23f262390527)
install module eror

**Comment by ERLANRAHMAT** [comment]
make?npm i or yarn

**Comment by RokhisAhmad** [comment]
> make?npm i or yarn

di panel auto install modul

**Comment by ERLANRAHMAT** [comment]
panel lu kali gw aman² aja tuh

**Comment by ErozeBotz** [comment]
> panel lu kali gw aman² aja tuh

keripik jembut
