### ISSUE TITLE
Error Module not found.

### ISSUE THREAD

**Issue by garuuuuuuuuuuuuuuuuuuuux** [ERLANRAHMAT/BETABOTZ-MD2#25]
Error Module not found.
1. ms
2. unpipe
3. ./types.json

Gatau ada lagi atau ga, karena stuck di nomor 3.

![WhatsApp Image 2023-10-08 at 19 07 10](https://github.com/ERLANRAHMAT/BETABOTZ-MD2/assets/142909854/b7f75866-3245-4058-ab3a-5dccbb34d4c0)

![WhatsApp Image 2023-10-08 at 19 08 12](https://github.com/ERLANRAHMAT/BETABOTZ-MD2/assets/142909854/5df702dd-f0b2-47c9-9bf5-6cb5c75c8623)
![WhatsApp Image 2023-10-08 at 19 07 49](https://github.com/ERLANRAHMAT/BETABOTZ-MD2/assets/142909854/c8560804-8bff-4a6d-a33b-630dcd02db6c)

**Comment by ERLANRAHMAT** [comment]
gw run aman tuh,panel lu ga support itu
