### ISSUE TITLE
prefix ask

### ISSUE THREAD

**Issue by ghost** [ERLANRAHMAT/BETABOTZ-MD2#6]
bisa tanpa prefix ga bang? jadi kalau pakai command gausah ada prefix nya kayak # / . - dll

**Comment by ghost** [comment]
sama kalau run scriptnya di replit, di terminalnya full kalimat "True" sampe overload dan berujung ga muncul QR bang

**Comment by ghost** [comment]
command .igstory error, .song .yt yang tittle gabisa :)

**Comment by ERLANRAHMAT** [comment]
> bisa tanpa prefix ga bang? jadi kalau pakai command gausah ada prefix nya kayak # / . - dll

Mungkin bisa

**Comment by ERLANRAHMAT** [comment]
> command .igstory error, .song .yt yang tittle gabisa :)

Igstory next update make apiku or scrape
.yt next juga

**Comment by ghost** [comment]
ok bang ditunggu next updatenya, btw di ig download ada yang kelebihan tanda ) kalau ga salah

**Comment by ERLANRAHMAT** [comment]
> ok bang ditunggu next updatenya, btw di ig download ada yang kelebihan tanda ) kalau ga salah

Ig story dh update
Downloader-ig skrg support
Ig photo
Ig video
Ig story
Ig reels

**Comment by ERLANRAHMAT** [comment]
> command .igstory error, .song .yt yang tittle gabisa :)

Song sama .yt di gw work coba lagi mungkin tadi server nya down

**Comment by ghost** [comment]
Siap bang, thank you

**Comment by ERLANRAHMAT** [comment]
> Siap bang, thank you

Cek new code ig soalnya yg lama ada sedikit bug

**Comment by ERLANRAHMAT** [comment]
> sama kalau run scriptnya di replit, di terminalnya full kalimat "True" sampe overload dan berujung ga muncul QR bang

Udah ga supp replit lagi

Perubahan

Need hosting yang support expresjs 

Bisa menjalankan environment port default rtxzy 8080

Hosting memiliki puppeteer

Ram lebih dari 1,5gb

**Comment by ghost** [comment]
Oooo gitu, sebenarnya okelah bang, makasih banyak infonya

**Comment by ERLANRAHMAT** [comment]
> Oooo gitu, sebenarnya okelah bang, makasih banyak infonya

Cek update cuy ada beberapa fitur add and fix bug
