### ISSUE TITLE
Bang Ko Eror Run Replit?

### ISSUE THREAD

**Issue by ERLANRAHMAT** [ERLANRAHMAT/BETABOTZ-MD2#7]
Script Ini Sudah Tidak Suport Replit Lagi Karena
Perubahan

Need hosting yang support expresjs 

Bisa menjalankan environment port default rtxzy 8080

Hosting memiliki puppeteer

Ram lebih dari 1,5gb

**Comment by hdiiofficial** [comment]
Kok di aku ga error bng biar error gimana

**Comment by 0zunu** [comment]
> Script Ini Sudah Tidak Suport Replit Lagi Karena Perubahan
> 
> Need hosting yang support expresjs
> 
> Bisa menjalankan environment port default rtxzy 8080
> 
> Hosting memiliki puppeteer
> 
> Ram lebih dari 1,5gb

run di cyclic apakah bisa?

**Comment by ERLANRAHMAT** [comment]
> > Script Ini Sudah Tidak Suport Replit Lagi Karena Perubahan
> > Need hosting yang support expresjs
> > Bisa menjalankan environment port default rtxzy 8080
> > Hosting memiliki puppeteer
> > Ram lebih dari 1,5gb
> 
> run di cyclic apakah bisa?

Belum coba

**Comment by 0zunu** [comment]
> > > Script Ini Sudah Tidak Suport Replit Lagi Karena Perubahan
> > > Need hosting yang support expresjs
> > > Bisa menjalankan environment port default rtxzy 8080
> > > Hosting memiliki puppeteer
> > > Ram lebih dari 1,5gb
> > 
> > 
> > run di cyclic apakah bisa?
> 
> Belum coba

hmm ok
